### ISSUE TITLE
pop-up content

### ISSUE THREAD

**Issue by britteckerstrom** [pennstategeog467/campus-map#20]
The idea is to create a highly functional, mobile-friendly (aka simple), and aesthetically pleasing pop-up that contains content associated with the buildings on campus. Here is some of the data I would like to include in the pop-ups: 
1. Overview - building pictures 
2. Details - tags in collaboration with Will - academic, residence, dining, athletic, etc. 
3. Departments/colleges within each building
4. Services - dining, computer labs, parking garages etc. (hours, menus, etc.)

**Comment by britteckerstrom** [comment]
![screen shot 2015-03-24 at 11 01 50 pm](https://cloud.githubusercontent.com/assets/11636009/6817643/0e89c740-d27a-11e4-9f1c-94f009421221.png)

**Comment by yalewilliams** [comment]
Are you planning on just making the pop-ups, populating them, or both?
