### ISSUE TITLE
Commonwealth campuses

### ISSUE THREAD

**Issue by leighhastings** [pennstategeog467/campus-map#24]
Compile the campus building shapefiles for each campus. Merge them into vector tiles. Merge tiles with Mapbox/Openstreetmap/Penn State Campus map.

Leigh and Adam

**Comment by aaronpdennis** [comment]
Rob from OPP shared this metadata with me about how they created the commonwealth campus datasets.

> The consultant that digitized the basemap features did so following a buffered campus boundary file, so each of the Commonwealth geodatabases has data for buildings, roads, etc that aren’t actually inside the campus boundary.  For buildings, the “LAYER” field will have the “C-BLDG-EXST-NONPSU” attribute if it is not a PSU building.  The other feature classes have a “PSU” field with a simple “YES” or “NO” to designate a PSU feature from a non-PSU feature.  I also added another folder to Box, “Commonwealth Campus Boundary” that contains a shapefile of the same name.
