### ISSUE TITLE
Golf Course Data Enrichment

### ISSUE THREAD

**Issue by brc5125** [pennstategeog467/campus-map#30]
The initial goal is to update the blue and white golf courses within open street map. This will involve manually collecting data such as tee boxes location blue, white, and red tee box yardage, hole numbers, par, doglegs, and any ancillary information deemed appropriate as the project progresses. 

In addition to this the golf courses themselves are outdated in terms of how features are represented. By using well known models such as Augusta National Golf Course, which is used for major play, the tee boxes will be drawn in the appropriate locations. The dogleg for each hole will also be represented by a white line drawn from the tee box to the green, ending at the hole, accompanied by the hole number. Originally the fairways themselves were simply represented by "area" instead of the provided OSM fairway feature type which will need to be updated for both courses.

Within each feature itself I will need to figure out the most appropriate way to add attributes in order to properly represent the newly acquired data. The yardage for each tea box and the par will be the main attributes I will be looking to add.

**Comment by aaronpdennis** [comment]
Some great thoughts here. Check to see if fairways in OSM should/can be represented with **both** area features and line features, not just one or the other.

**Comment by brc5125** [comment]
I haven't been able to find any documentation discussing this yet, however, upon looking at two golf courses used during the major championships I found that both use area and lines to represent each hole. This allows the full area as well as the dogleg and hole number to be represented without selecting any features. I will continue to try and find any direct information regarding the appropriateness of this technique.

![augustamodel_teebox](https://cloud.githubusercontent.com/assets/11635981/6848513/0f510c44-d3a4-11e4-8ac6-e9f55f359771.JPG)
![royalancientmodel](https://cloud.githubusercontent.com/assets/11635981/6848520/23848b5a-d3a4-11e4-9ceb-e2c841e3efb4.JPG)
